2 nc news
crossmatthew/nc-news pull request #3
Opened 2023-11-20 14:41 UTC by crossmatthew

2023-11-20 15:10 UTC, MKD01 requested changes
Good work so far, but I would like to see your tests updated before you merge this in, so please make the requested changes and re-submit this pr

2023-11-20 15:10 UTC, MKD01 commented on __tests__/app.test.js
> +            )
This expect statement is specifically checking that the first topic has the keys "slug" and "description", but we should instead be expecting every topic to have these keys and ideally we should be expecting what the values of these are as well. 

I would recommend looking into .toMatchObject for this.

2023-11-20 15:10 UTC, MKD01 commented on controllers/errorhandlers.js
> +}
This shouldnt be here yet. We should only be adding code that has been tested, which this cannot be tested for with the current endpoints you have.

2023-11-20 15:10 UTC, MKD01 commented on __tests__/app.test.js
> +            expect(Object.keys(body[0]))
We should expect body to have a key of topics with the array of topics as its value.

2023-11-21 10:12 UTC, saimakhanom commented
Well done for incorporating feedback - all good to merge!

2023-11-21 10:14 UTC, merged